### PR TITLE
fix: floating div size

### PR DESCRIPTION
**Pull request by rahilansari261**
[screen-capture.webm](https://github.com/ArslanYM/StarterHive/assets/12849916/bca4537c-c8e3-48c0-bca8-c32479706627)
### What does this PR do?

bug fixes
floatind div size fixes

### CODE REVIEW

**Review by ArslanYM — COMMENTED** [review]
For some reasons, in the vercel preview there is no chagne

**Comment by rahilansari261** [comment]
again sizes are not changing
what could be the reason ? @ArslanYM ?
my fork repo says it is 1 commit ahead 
how to resolve that any idea

**Comment by ArslanYM** [comment]
> again sizes are not changing what could be the reason ? @ArslanYM ? my fork repo says it is 1 commit ahead how to resolve that any idea

Yes obviously your fork woudl be one commit ahead, but im not sure why this is happening

**Comment by rahilansari261** [comment]
How can I synk with upstream any idea

**Comment by ArslanYM** [comment]
> How can I synk with upstream any idea

If you havent added an remote upstream link to you branch here's how you can: 
https://stackoverflow.com/questions/8948803/what-does-git-remote-add-upstream-help-achieve

**Comment by rahilansari261** [comment]
I did 
I have 2 remote one is origin (forked one)
and second is upstream that is the original repo

**Comment by rahilansari261** [comment]
I think merging will resolve it .
Let's merge it we'll see

**Review by ArslanYM — APPROVED** [review]
Lets try

**Pull request merged**
