### PR TITLE
Add Loader Component

### LINKED ISSUE #162: ⭐FEAT: Loader Component for contributors page
## Feature Request
A loader component for the [contributors page](https://starter-hive.vercel.app/contributors) would be cool. Even though the results fetched are pretty quick, it can take up to a maximum of one to two seconds for it to complete. 

image
image

### Proposal
* A loader component to be added

### PR DESCRIPTION
**Pull request by masif2002**
Fixes #162 
* Implemented Loader Component for Contributors Page
loader

### CODE REVIEW

**Comment by masif2002** [comment]
@ArslanYM why is there no preview available by Vercel?

**Comment by ArslanYM** [comment]
> @ArslanYM why is there no preview available by Vercel? 

I don't understand, for some PRs including yours. Its not giving a preview

**Comment by masif2002** [comment]
Check this out: https://vercel.com/guides/why-aren-t-commits-triggering-deployments-on-vercel
> this occurs when pre-deployment validation fails, for example, an incorrectly formatted vercel.json file.

This could be a reason :/

**Comment by masif2002** [comment]
> If you receive a pull request from a fork of your repository that includes a change to the vercel.jsonfile or the Project has Environment Variables, ​Vercel will require authorization from you or a Team Member to deploy the pull request.
https://vercel.com/docs/concepts/projects/overview#git-fork-protection

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by masif2002** [comment]
@ArslanYM what was the issue with Vercel?

**Comment by ArslanYM** [comment]
Since you made changes to the vercel.json file in the last PR. Now everytime a PR is raised , the changes to vercel.json are reflected in the PR. Probably that or otherwise idk

**Pull request merged**
