### PR TITLE
Enhanced the search bar and scrollbar

### PR DESCRIPTION
**Pull request by kaur-rajdeep**
Issue Number #300 resolved

I've made the following changes:
-enhanced the search bar
-enhanced the scrollbar
-added a search icon

Screenshots:
image

Thank you :)

### CODE REVIEW

**Review by ArslanYM — CHANGES_REQUESTED** [review]
The text color of the search bar is not visible for dark mode.

***

**Comment by kaur-rajdeep** [comment]
Sorry for not looking into it, here I've fixed.
 Hope this looks good :)
image
image

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by ArslanYM** [comment]
Great Work!! Thankyou for your contribution

**Pull request merged**
