### PR TITLE
Homepage tweaks for mobile

### PR DESCRIPTION
**Pull request by rahilansari261**
### What does this PR do ?

it solves the below issues and some other issues 
https://github.com/ArslanYM/StarterHive/issues/179

1. fix: below 323px navbar wraps now
2. fix: added a utility class to unset width as we go from sm to md devices
3. fix: margin removed from header logo
4. fix: header logo added
5. fix: hero section text width limited after md devices
6. fix: footer logo and title order changed

### CODE REVIEW

**Comment by ArslanYM** [comment]
@rahilansari261 Some new changes were introduced to the Header , Can you resolve the conflicts and make sure the new changes are added are well in this PR. Also, I think we agreed on keeping the commits as less as possible. See to that next time.

**Comment by rahilansari261** [comment]
> @rahilansari261 Some new changes were introduced to the Header , Can you resolve the conflicts and make sure the new changes are added are well in this PR. Also, I think we agreed on keeping the commits as less as possible. See to that next time.

i get your point regarding commits i was just doing some experiment .

**Comment by ArslanYM** [comment]
> > @rahilansari261 Some new changes were introduced to the Header , Can you resolve the conflicts and make sure the new changes are added are well in this PR. Also, I think we agreed on keeping the commits as less as possible. See to that next time.
> 
> i get your point regarding commits i was just doing some experiment .

Great Work! Looks good on mobile too. Well done @rahilansari261

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
