### PR TITLE
Fix: Vercel - 404 NOT_FOUND

### LINKED ISSUE #158: 🔴 BUG: 404 NOT_FOUND
## Description
A 404 Error when tried to navigate to a page directly by URL. 
Try this: https://starter-hive.vercel.app/contributors

image

### Additional context
* This is probably due to the routing on server side 
* We need to add a redirect rule to route back to the root URL `/` regardless of the route entered

### PR DESCRIPTION
**Pull request by masif2002**
Fixes #158 
* Added `vercel.json` file to redirect to root URL on visiting any path

### CODE REVIEW

**Comment by ArslanYM** [comment]
@masif2002  Make these changes to your fork branch. Youre trying to make changes directly to my repo.

**Comment by masif2002** [comment]
I think I did add it to my fork and raised a PR from there
image

**Comment by MuhammadRabi** [comment]
> I think I did add it to my fork and raised a PR from there
> image
> 

I think you should raise the PR from the original repo.

**Comment by ArslanYM** [comment]
@masif2002 Raise a new PR , it seems like this one cannot be merged

**Pull request closed without merging**
