### PR TITLE
Reduced search bar width

### PR DESCRIPTION
**Pull request by farhadjaman**

### CODE REVIEW

**Comment by farhadjaman** [comment]
I have created a PR requested.Kindly give it a check and let me know.

**Comment by ArslanYM** [comment]
@farhadjaman Do you think this PR justifies 2000 code changes?
Please raise a PR with only the relevant changes. 
wtf

**Comment by farhadjaman** [comment]
I think i can do better than that.

**Comment by ArslanYM** [comment]
> I think i can do better than that.

Just make the required changes in the UI of the search bar. That would suffice.

**Pull request closed without merging**
