### PR TITLE
Add search input to filter languages

### LINKED ISSUE #372: ⭐FEAT: Search language
**Is your feature request related to a problem? Please describe.**
When I want to filter the projects, I must scroll and find word by word the filter I want.

**Describe the solution you'd like**
A search input inside of the dropdown that list the filters to be possible to search the filter the user want.

**Additional context**
I can contribute with this feature opening a Pull Request 😊

### PR DESCRIPTION
**Pull request by marcelorafaelfeil**
Add a search input to filter the languages and topics.

https://github.com/ArslanYM/StarterHive/assets/12664500/e92cf95b-c686-402d-832d-ba61f4da2754

Resolve #372

### CODE REVIEW

**Comment by marcelorafaelfeil** [comment]
Hi @ArslanYM,

Any problem with my PRs? 😕

**Comment by ArslanYM** [comment]
> Hi @ArslanYM,
> 
> Any problem with my PRs? 😕

This feature has already been implemented. What's new in this?

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by ArslanYM** [comment]
Please resolve the conflcts in this PR @marcelorafaelfeil

**Comment by marcelorafaelfeil** [comment]
> Please resolve the conflcts in this PR @marcelorafaelfeil

Done!

**Pull request merged**
