### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by turtlebeasts**
A filter feature is added to the IssueList page

### CODE REVIEW

**Comment by ArslanYM** [comment]
@turtlebeasts Have your read the contribution guidelines of this project. Before adding a feature, you must raise an issue for it and get assigned to it. I think you must do the same , only then can I approve this PR.

**Comment by turtlebeasts** [comment]
I'm sorry I didn't see the guidelines, I'll surely raise an issue for this feature. Thanks

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by turtlebeasts** [comment]
Thanks a lot

**Pull request merged**
