### PR TITLE
app navigations and issue list

### PR DESCRIPTION
**Pull request by nadeem099**
issue #111 #115 

- added navigation to the links of website
- added a json object which will be used to manually add the issues to the website
- displayed the issue cards on issues page
- changed few file names to align with the feature names

### CODE REVIEW

**Review by rahilansari261 — COMMENTED** [review]
@nadeem099 you need to first pull the code base seems like old code is showing up again 
what you say @ArslanYM ?

**Comment by ArslanYM** [comment]
> @nadeem099 you need to first pull the code base seems like old code is showing up again what you say @ArslanYM ?

Its working fine , I dont understand what youre saying?

**Review by ArslanYM — APPROVED** [review]
Needs some minor fixed but works for now.

**Comment by rahilansari261** [comment]
@ArslanYM  check the website floating divs not there .

**Pull request merged**
