### PR TITLE
Enhanced Filter Dropdown

### LINKED ISSUE #257: ⭐FEAT: filter button enhancement.
**Is your feature request related to a problem? Please describe.**
The filter button doesnt look good rn.

**Describe the solution you'd like**
enhance the UI of the the filter button.

Screenshot 2023-06-18 225054

### PR DESCRIPTION
**Pull request by shyamtawli**
This PR fixes #257 

I not familiar with Tailwind CSS but by reading some docs I have tried improving it. More enhancement can be done but first I have to learn Tailwind CSS. 

Thank you for the assigning me. I have come to know about some basics of Tailwind while working on it.

### CODE REVIEW

**Comment by turtlebeasts** [comment]
It looks pretty good in light mode, but it doesn't contrast well in dark mode

**Comment by shyamtawli** [comment]
@turtlebeasts I will look into it.

**Comment by shyamtawli** [comment]
@turtlebeasts Have a look now. I have made the changes.

**Comment by turtlebeasts** [comment]
bro @shyamtawli I'm not the admin, @ArslanYM please have a look at the PR

**Comment by ArslanYM** [comment]
This feature needs a discussion. I will be closing this PR, you can raise a discussion for the same.

**Pull request closed without merging**
