### PR TITLE
fixed issue #245

### PR DESCRIPTION
**Pull request by harshsbhandari**
Added hover property

### CODE REVIEW

**Comment by ArslanYM** [comment]
@harshsbhandari Looks like youve tried to change the theming of the project. Please stick the original theming. On hover , the button should become :
*** 
this`
***

this2


*** 
Thankyou

**Review by ArslanYM — CHANGES_REQUESTED** [review]
Please make changes in the code..

**Comment by harshsbhandari** [comment]
Done as instructed please check

**Comment by harshsbhandari** [comment]
@ArslanYM done the required changes

**Review by ArslanYM — APPROVED** [review]
LGTM  👍🏻

**Pull request merged**
