### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by karthiknadar1204**
Screenshot 2023-05-26 at 11 11 38 AM

### CODE REVIEW

**Comment by karthiknadar1204** [comment]
How can i reslove this conflict

**Comment by ArslanYM** [comment]
> This branch has conflicts that must be resolved

https://github.com/githubteacher/github-for-developers-sept-2015/issues/648

**Comment by karthiknadar1204** [comment]
Will do by evening @ArslanYM

**Comment by karthiknadar1204** [comment]
Pushing the changes again @ArslanYM 
Had to redo the navbar, lost the branch

**Comment by ArslanYM** [comment]
@karthiknadar1204  Sorry to say, but this PR must be closed. The quality of this PR is very low. The changes you made are not responsive, you can see below. This PR has merge conflicts as well.

**Comment by karthiknadar1204** [comment]
#100

**Comment by ArslanYM** [comment]
This PR is close worthy.

**Pull request closed without merging**
