### PR TITLE
Fix: Fixed project name

### PR DESCRIPTION
**Pull request by promise-dash**
Fixed issue #201
Added necessary spacing in the name at the footer.

### CODE REVIEW

**Comment by ArslanYM** [comment]
@promise-dash  I dont think thats what the issue was. The issue was this:
in header there a  space  " " :


In footer theres no space:

**Comment by promise-dash** [comment]
Oh, my bad. Now I get it

**Review by ArslanYM — CHANGES_REQUESTED** [review]
Add a space to both!

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by promise-dash** [comment]
Thanks for merging my PR.
I am glad to know that my contribution was helpful.

**Comment by ArslanYM** [comment]
> Thanks for merging my PR. I am glad to know that my contribution was helpful.

Great work @promise-dash. Looking forward for more  contributions from you. Don't forget to start the repo and share it with your friends.

**Pull request merged**
