### PR TITLE
Feat:Project Links open in new tab

### LINKED ISSUE #346: 🔴[BUG] Enhance User Experience by Opening Projects in New Tabs
### Description of the bug

For a smoother user experience in the Projects tab, it would be more convenient if clicking on a project opens it in a new tab instead of the same one.

### Please add screenshots (if applicable)

_No response_

### Add any other context about the problem here

_No response_

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by kaushik17tripathi**
##What does this PR do?
This PR enhances link to open in new tab

Fixes #346

##Type of change
-Enhancement

##How should this be tested
-Go to Home Page.
-Click on Projects tab.
-Click on any Project Card.

### CODE REVIEW

**Review by ArslanYM — CHANGES_REQUESTED** [review]
This PR has conflicts with the main branch.

**Comment by kaushik17tripathi** [comment]
@ArslanYM Is the issue resolved because in the forked repository it show branch is up to date with main

**Comment by amanrajrana** [comment]
**Why are the Cards Appearing Uneven?**

image

Dear @kaushik17tripathi, I would suggest creating a fresh new PR. You can follow these steps for an easier process:

1. Navigate to your profile where you have forked the repository and "sync" the `main` branch.
2. Open the codebase in your favourite IDE and execute the following commands:
   ```
   git checkout main
   git pull origin main
   ```
3. Create a fresh new branch.
4. Implement your changes.
5. Commit your changes.
6. Push the branch to the repository.
7. Initiate a new Pull Request (PR).

**Comment by kaushik17tripathi** [comment]
@ArslanYM @amanrajrana Created fresh PR now there are no conflicts.

**Comment by kaushik17tripathi** [comment]
#354

**Pull request closed without merging**
