### PR TITLE
Integrated Prettier and Husky for code formatting

### PR DESCRIPTION
**Pull request by NextThread**

### CODE REVIEW

**Comment by NextThread** [comment]
@ArslanYM please review my pR

**Comment by ArslanYM** [comment]
@NextThread , Can we have a discussion about this before merging this PR?

**Comment by NextThread** [comment]
> @NextThread , Can we have a discussion about this before merging this PR?

sure

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
