### PR TITLE
feat: Changed Font style of main text on hero.

### PR DESCRIPTION
**Pull request by Kruthardh11**
I highlighted the words 'Open source' and gave some margin for spacing.

### CODE REVIEW

**Comment by Kruthardh11** [comment]
added the zoom out animation and golden color.

**Comment by ArslanYM** [comment]
@Kruthardh11 Looks like this PR has merge conflicts. Please check.

**Comment by Kruthardh11** [comment]
i have resolved merge conflicts

**Review by ArslanYM — CHANGES_REQUESTED** [review]
Need to make changes.

**Comment by ArslanYM** [comment]
Youve made a typo as well as the padding to the word open source isnt looking well. 

wtf

**Comment by Kruthardh11** [comment]
sh-2
it shows like this for me

**Comment by ArslanYM** [comment]
> sh-2 it shows like this for me

Thats because you havent made it responsive for all screens.

**Comment by Kruthardh11** [comment]
i sorted the the typo and made it responsive. let me know if any changes needed.

**Comment by Kruthardh11** [comment]
I resolved the conflicts. @ArslanYM please check it out

**Comment by ArslanYM** [comment]
@Kruthardh11 Before I merge this PR , I want you to go through few documentation for further contributions. This way it would be easier for me to manage this project. 
Links :
-  [Commit](https://medium.com/@steveamaza/how-to-write-a-proper-git-commit-message-e028865e5791)
- [PR](https://www.pullrequest.com/blog/writing-a-great-pull-request-description/)
- [merge conflicts](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github)

**Comment by Kruthardh11** [comment]
Surely.
 I apologise for my mistakes. I'm considerably new to open source. I'm still learning. Thank you.

**Comment by ArslanYM** [comment]
> Surely. I apologise for my mistakes. I'm considerably new to open source. I'm still learning. Thank you.

I understand youre new to open source , thats why this is the best time to understand these practices. You dont owe an apology to anyone. Grow as you learn. Thanks

**Pull request merged**
