### PR TITLE
added my profile in contributers list

### PR DESCRIPTION
**Pull request by yashhhh04**
LEARNING HOW TO CONTRIBUTE

### CODE REVIEW

**Review by ArslanYM — CHANGES_REQUESTED** [review]
Add a space before your name to make it a bullet point inside Y

**Review by ArslanYM — CHANGES_REQUESTED** [review]
Add a space before your name to make it a bullet point inside Y

**Comment by yashhhh04** [comment]
how can i edit my pull request on browser

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Comment by ArslanYM** [comment]
@yashhhh04 Thankyou for your contribution!!

**Pull request merged**
