### PR TITLE
Project Page Responsiveness Added. fixes #319

### LINKED ISSUE #319: [BUG]: /projects section isnt responsive
### Description of the bug

TODO:
- Constant size of projectcard throughout the section 
- keep placeholders for logo that are not rendering 

### Add any other context about the problem here

_No response_

### Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/ArslanYM/StarterHive/blob/main/CONTRIBUTING.md)
- [X] I have checked the existing [issues](https://github.com/ArslanYM/StarterHive/issues)
- [ ] I am willing to work on this issue (optional)

### PR DESCRIPTION
**Pull request by khuzaima-a**
SS

SS2

### CODE REVIEW

**Comment by khuzaima-a** [comment]
#319 Fixed

**Review by ArslanYM — CHANGES_REQUESTED** [review]
I was hoping for tailwindCSS to be used instead of pure CSS.

**Comment by khuzaima-a** [comment]
#319  Converted Pure CSS to Tailwind CSS

**Review by ArslanYM — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
